### ISSUE TITLE
Provide some installation instructions

### ISSUE THREAD

**Issue by secondfolder** [metafetish/buttplug-playground#40]
Due to the [JS examples currently being broken](https://github.com/buttplugio/buttplug-developer-guide/issues/39) I wanted to spin this up locally so I could understand how to run buttplug.io in a browser (and debug why something wasn't working for me in an app I'm working on) but I was unable to install this due to errors.

After running `npm install` I tried running `npm run start` and go this error:
```
> buttplug-playground@0.0.1 start
> yarn build:config && webpack-dev-server --hot --config build/webpack.base.js

yarn run v1.22.10
$ node build/generate_config.js
Done in 0.72s.
/private/tmp/buttplug-playground/build/webpack.base.js:120
      throw new Error('No matching configuration was found!');
      ^

Error: No matching configuration was found!
    at module.exports (/private/tmp/buttplug-playground/build/webpack.base.js:120:13)
    at handleFunction (/private/tmp/buttplug-playground/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/private/tmp/buttplug-playground/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/private/tmp/buttplug-playground/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /private/tmp/buttplug-playground/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/private/tmp/buttplug-playground/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at Object.<anonymous> (/private/tmp/buttplug-playground/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.2.0
```

Playing around a bit I added `--env development` to the end of the package.json start script which progressing things but then I ran into this:
 
```
> buttplug-playground@0.0.1 start
> yarn build:config && webpack-dev-server --hot --config build/webpack.base.js --env development

yarn run v1.22.10
$ node build/generate_config.js
Done in 0.60s.
✖ ｢wdm｣: Hash: fb661648ec64f6a8fa0f
Time: 8331ms
Built at: 08/01/2022 10:05:30 am
Entrypoint main [big] = build.js (prefetch: 0.build.js ce4359e427158deb609d.module.wasm)
[0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/main.ts 52 bytes {main} [built]
[./node_modules/buttplug/dist/module/index.js] 506 bytes {main} [built]
[./node_modules/matomo-tracker/index.js] 3.87 KiB {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/viewport-units-buggyfill/viewport-units-buggyfill.js] 15.2 KiB {main} [built]
[./node_modules/vue-awesome/components/Icon.vue] 905 bytes {main} [built]
[./node_modules/vue/dist/vue.runtime.esm.js] 222 KiB {main} [built]
[./node_modules/vuetify/lib/index.js] 236 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./src/main.ts] 1.46 KiB {main} [built]
    + 567 hidden modules

ERROR in ./src/App.vue?vue&type=style&index=0&lang=css& (./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=css&)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /private/tmp/buttplug-playground/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/private/tmp/buttplug-playground/node_modules/css-loader/dist/index.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
 @ ./src/App.vue?vue&type=style&index=0&lang=css& (./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=css&) 2:12-236 9:17-24 13:7-14 45:20-27 47:4-60:5 49:6-59:7 50:38-45 56:26-33 58:21-28 68:15-22
 @ ./src/App.vue?vue&type=style&index=0&lang=css&
 @ ./src/App.vue
 @ ./src/main.ts
```

No idea if I'm doing the right thing to get the app up and running so some installation instructions would be very helpful to do if it's a PEBKAC issue or a bug. For reference I'm running on macOS 10.15.7 with node v17.2.0.

**Comment by qdot** [comment]
Oh yeah Playground is hideously broken right now. If you want a simple example to start with, check out this glitch example:

https://glitch.com/edit/#!/how-to-buttplug
